### ISSUE TITLE
Feature request: CLI without running server

### ISSUE THREAD

**Issue by ku3o** [tmavre/currency_converter_web_api-cli#4]
It's an overkill to run a flask server just to convert a currency in a command line. I would like to have convert currencies without a need for a running flask service.

**Comment by tmavre** [comment]
@ku3o 
There wasn't any server running in cli. Either way, with #6 I put the server and the client in their own path to be less confusing for the user.

**Comment by ku3o** [comment]
Sorry, maybe I wasn't clear enough. 

My point was, that for running a CLI `client` successfully, it's necessary to have a Flask `server` running. If the Flask `server` is not running, the client cannot reach the server and no currency conversion is possible.

My feature request was that the `client` runs without a necessity of having the flask `server` running in a background. 

I hope it's clearer, now. 

Can you adjust the code like that, please?
